name: Matrix Demo
on: push
jobs:
  build:
    # Queremos ejecutar este job con la ayuda de un matrix.
    # La idea detrás de un matrix es que se puede ejecutar el mismo trabajo con configuraciones diferentes,
    # por ejemplo diferentes runs-on o diferentes versiones de Node, a la vez.
    # Esto se hace añadiendo el field strategy al job, seguido de matrix y debajo se añade cualquier key
    # que queramos cambiar y para la que, para ese nuevo valor, queramos ejecutar el job, que
    # se ejecutará por defecto en paralelo.
    # Indicar que por defecto, si un job falla, los otros se cancelan. Para evitar ese comportamiento se puede usar
    # continue-on-error a true a nivel de job.
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        # Hay dos características relacionadas a matrix.
        # 1. Se puede añadir la key reservada include. Permite añadir una lista con guiones y clave-valor que deben incluirse
        #    sin añadir un puñado de nuevas combinaciones. En este ejemplo se instalará la versión de node 18 solo para ubuntu (no windows)
        #    Se pueden incluir nuevas claves no especificadas en la matrix (por ejemplo, podríamos incluir: npm: 6)
        # 2. Se puede añadir la key reservada exclude. Permite excluir combinaciones.
        #    En el ejemplo no se va a realizar la ejecución de node 12 con windows-latest.
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    # Ahora se puede establecer el runner de forma dinámica
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          # Igual aquí ahora establecemos el valor de forma dinámica según las valores informados en matrix
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
